### ISSUE TITLE
Wrong LR Test for Interceptless Covariate Model

### ISSUE THREAD

**Issue by boyiguo1** [lmweber/nnSVG#15]
There is a corner case for `nnSVG` where the LR test would be wrong. The corner case is happens when testing the spatial effect with an intercept-less covariate model (see code example below). This bug is due to the current implementation of the null model, i.e. the `lm` model, will include intercept by default regardless if there's an intercept term in the design matrix `X`.
https://github.com/lmweber/nnSVG/blob/0ea970c78577222bc8334a6e570a99e898387404/R/nnSVG.R#L285 

The bug can be fixed by changing the line to `as.numeric(logLik(lm(y_i ~ X-1)))` without modifying other lines of code.

## Why is this bug important?
With the proposed fix, it would be easy to implement a weighted version of the `nnSVG` model.

## Code Example
```R
library(SpatialExperiment)
library(STexampleData)
library(scater)
library(nnSVG)

spe <- Visium_humanDLPFC()

# preprocessing steps

# keep only spots over tissue
spe <- spe[, colData(spe)$in_tissue == 1]

# skip spot-level quality control, since this has been performed previously
# on this dataset

# filter low-expressed and mitochondrial genes
spe <- filter_genes(spe)

# calculate logcounts (log-transformed normalized counts) using scran package
# using library size factors
spe <- computeLibraryFactors(spe)
spe <- logNormCounts(spe)

# select small number of genes for faster runtime in this example
set.seed(123)
ix <- sample(seq_len(nrow(spe)), 4)
spe <- spe[ix, ]

# run nnSVG
# Does not affect intercept-only model
set.seed(123)
spe1 <- nnSVG(spe)

set.seed(123)
spe2 <- nnSVG(spe, X = matrix(1, nrow = ncol(spe), ncol = 1))


# Covariate Model ---------------------------------------------------------

spe_cov <- spe[, !is.na(spe$ground_truth)]
X <- model.matrix(~ colData(spe_cov)$ground_truth)

# Intercept Model
set.seed(123)
spe3 <- nnSVG(spe_cov, X = X)


# Interceptless Model
set.seed(123)
spe4 <- nnSVG(spe_cov, X = X[,-1])

# Different model (as expected)
rowData(spe3)$LR_stat
rowData(spe4)$LR_stat

# Null model will be the same model (not as expected)
rowData(spe3)$loglik_lm
rowData(spe4)$loglik_lm

# different nnSVG models (as expected)
rowData(spe3)$loglik
rowData(spe4)$loglik
```

## Root Cause
The linear regression function `lm` does report any error when collinearity exists in the design matrix, where the model technically shouldn't fit at all.

```{R}
# LM Example
set.seed(1)
x <- rep(1, 100)
y <- rnorm(100)
lm(y~x)     # Doesn't report error 
lm(y~x-1)
```

So technically, the `lm` model for `spe1` have a design matrix that contains two intercepts. Because `lm` model will detect colinearity in the model and only use one of the variables, the loglikelihood is still correct.

**Comment by lmweber** [comment]
Thanks for submitting this. Yes, this all makes sense (as we discussed last week).

This is now updated in version 1.5.3, which I have pushed to GitHub and Bioconductor (devel 3.18) today. This version should be installable from GitHub now, and through the Bioc installers in 1-2 days.

I also added some updated examples in the main `nnSVG()` function and more stringent unit tests (checking some specific p-values) to make sure nothing unexpected went wrong.

cc also @stephaniehicks

**Comment by stephaniehicks** [comment]
Thanks @lmweber! Tagging @kinnaryshah too.

**Comment by kinnaryshah** [comment]
Thanks!

**Comment by lmweber** [comment]
For future reference -- main change is in this commit: https://github.com/lmweber/nnSVG/commit/9d8905752a74405e732fac0a3fa8f5a9a0c8300a
