### ISSUE TITLE
Problem with more than two spatial coordinates

### ISSUE THREAD

**Issue by const-ae** [lmweber/nnSVG#18]
Hi Lukas,

first of all congratulations on the nice paper. 

I wanted to try your package on a dataset that isn't actually spatial data but where I similarly want to detect the variation of values as a function of their location. The main difference is that my locations are usually more than 2-dimensional.

In your paper, you write that the algorithm can in principle be generalized to more than two dimensions, but when I try to run `nnSVG` with a more than 2-dimensional `spatialCoords`, `BRISC_order` throws an error.

Do you have any suggestions how to work around that?

Best,
Constantin

**Comment by lmweber** [comment]
Hi @const-ae , great to hear from you and thanks for your interest!

Yes, in the paper we mention that the approach could in principle be generalized to more than 2 dimensions. However I think we were referring more to the underlying mathematical approach here. I don't think the code is likely to support 3 dimensions in its current form -- probably the `BRISC_order()` and `BRISC_neighbor()` steps specifically would need to be adapted.

I don't have any good suggestions for how to do this unfortunately. I suspect it could be quite complicated.

Alternatively maybe (for a given dataset) it could also be possible to do something similar to `BRISC_order()` and `BRISC_neighbor()` manually, and then use this as the input for the rest of the model fitting, i.e. the core of the model fitting at https://github.com/lmweber/nnSVG/blob/devel/R/nnSVG.R#L254-L266 and then the likelihood ratio statistics at https://github.com/lmweber/nnSVG/blob/devel/R/nnSVG.R#L343.

I'm not sure this helps very much, apologies -- but I think if you could find a way to solve the ordering of coordinates and the sets of nearest neighbors in higher dimensions, then the rest of it may be feasible.

**Comment by const-ae** [comment]
Thanks for the comprehensive response :)

>  I don't think the code is likely to support 3 dimensions in its current form -- probably the BRISC_order() and BRISC_neighbor() steps specifically would need to be adapted.
> I don't have any good suggestions for how to do this unfortunately. I suspect it could be quite complicated.

Okay, I was already afraid this would be the case. I just wanted to check because it would have been convenient for my application if I could have just relied on some existing tooling.

> I think if you could find a way to solve the ordering of coordinates and the sets of nearest neighbors in higher dimensions, then the rest of it may be feasible.

I will try to think it through, but I assume the ordering of the coordinates will be tricky (finding the nearest neighbors in high dimensions is surprisingly [easy](https://github.com/spotify/annoy), though).

**Comment by stephaniehicks** [comment]
hi all! My two cents are that @const-ae it might be useful to open up a github issue in BRISC (https://github.com/ArkajyotiSaha/BRISC) to see if it's something the authors are thinking about or maybe will be thinking about. There are many data types with more than 2 spatial coordinate dimensions and it might be worth at least asking if this is something on their radar?

**Comment by lmweber** [comment]
Hi all, thanks for the comments.

Another thing to mention is that the model is surprisingly robust to the exact choice of ordering scheme for the coordinates, as discussed in @abhirupdatta 's original paper on NNGPs ([Datta et al. 2016](https://www.tandfonline.com/doi/abs/10.1080/01621459.2015.1044091)).

So maybe you could start with a simple ordering scheme such as the sum of coordinates (which is the default in `BRISC_order()`). I think this would make sense in 3 dimensions. I'm not sure if you also have an application with much higher dimensionality though (>100 dims), in which case the curse of dimensionality could also become a problem.
