### ISSUE TITLE
error when using matrix as input

### ISSUE THREAD

**Issue by haotian-zhuang** [lmweber/nnSVG#19]
Hi Lukas,

Thank you for developing this great tool! When I use gene expression matrix as input, it returns following error message after running a long time. I suspect in line 282, when the input is not a `SpatialExperiment` object, `assayNames(spe)` will return error. Could you please check and fix if needed?

Thanks,
Haotian

`Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'assayNames': object 'spe' not found`

https://github.com/lmweber/nnSVG/blob/e26ed63be0909e8acc3d16d3cfa9b8ebda2a73aa/R/nnSVG.R#L282

**Comment by lmweber** [comment]
Hi @haotian-zhuang , apologies for the delay, and thanks for reporting this issue. This is now fixed and merged from the updates in pull request https://github.com/lmweber/nnSVG/pull/20. The updates will be installable from Bioc in 1-2 days after they have gone through the Bioc build system, and are also available now from GitHub. Please let me know if there are any further issues. Thank you!
