### ISSUE TITLE
Computational Complexity of NNGP

### ISSUE THREAD

**Issue by zhengxiaoUVic** [lmweber/nnSVG#21]
Hello, Dr. Weber.

Upon reviewing Weber et al. (2023, p. 9), it is noted that "the computational complexity of the model fitting is _O_(_n_ * _m_^3 ), where _n_ represents the number of spatial locations, and _m_ the number of nearest neighbors." I question whether it should instead be _O_(_n_ * _m_^2 ). However, the paper does not detail the specific form of the scalable approximation applied to the GP precision matrix. Thanks.

Datta, A., Banerjee, S., Finley, A. O., & Gelfand, A. E. (2016). Hierarchical nearest-neighbor Gaussian process models for large geostatistical datasets. _Journal of the American Statistical Association_, _111_, 800-812. DOI: 10.1080/01621459.2015.1044091

Weber, L. M., Saha, A., Datta, A., Hansen, K. D., & Hicks, S. C. (2023). nnSVG for the scalable identification of spatially variable genes using nearest-neighbor Gaussian processes. _Nature Communications_, _14_, 1-12. DOI: 10.1038/s41467-023-39748-z

Zhang, L. (2018). _Nearest Neighbor Gaussian Processes (NNGP) Based Models in Stan_. https://mc-stan.org/users/documentation/case-studies/nngp.html

**Comment by zhengxiaoUVic** [comment]
Okay, I found the argument regarding O(_n_ * _m_^3) (Finley et al., 2019, p. 403).

Finley, A. O., Datta, A., Cook, B. D., Morton, D. C., Andersen, H. E., & Banerjee, S. (2019). Efficient algorithms for Bayesian nearest neighbor Gaussian processes. _Journal of Computational and Graphical Statistics_, _28_, 401-414. DOI: 10.1080/10618600.2018.1537924.

**Comment by zhengxiaoUVic** [comment]
Okay, I found the argument regarding O(_n_ * _m_^3) (Finley et al., 2019, p. 403).

Finley, A. O., Datta, A., Cook, B. D., Morton, D. C., Andersen, H. E., & Banerjee, S. (2019). Efficient algorithms for Bayesian nearest neighbor Gaussian processes. _Journal of Computational and Graphical Statistics_, _28_, 401-414. DOI: 10.1080/10618600.2018.1537924.

**Comment by lmweber** [comment]
Hi @zhengxiaoUVic , that's great, thanks for letting me know and thank you for your interest!
